# Generated by Django 6.0.6 on 2026-06-08 05:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Number',
            fields=[
                ('value', models.SmallIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
            ],
            options={
                'verbose_name': 'Number',
                'verbose_name_plural': 'Numbers',
                'db_table': 'number',
                'ordering': ['value'],
            },
        ),
    ]
