# Generated by Django 6.1 on 2026-08-09 05:49

import core.utils.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numero',
            fields=[
                ('valor', models.SmallIntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(99)])),
            ],
            options={
                'verbose_name': 'Número',
                'verbose_name_plural': 'Números',
                'db_table': 'numero',
                'ordering': ['valor'],
            },
        ),
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('referencia', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('data', models.DateField()),
            ],
            options={
                'verbose_name': 'Sorteio',
                'verbose_name_plural': 'Sorteios',
                'db_table': 'sorteio',
                'ordering': ['-referencia', '-data'],
            },
        ),
        migrations.CreateModel(
            name='Apostador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=15, unique=True, validators=[core.utils.validators.validar_username])),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Apostador',
                'verbose_name_plural': 'Apostadores',
            },
        ),
        migrations.CreateModel(
            name='Aposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(default=django.utils.timezone.localdate)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('inicial', models.PositiveIntegerField()),
                ('final', models.PositiveIntegerField()),
                ('espelho', models.BooleanField(default=True)),
                ('apostador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apostas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aposta',
                'verbose_name_plural': 'Apostas',
                'db_table': 'aposta',
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='ApostaNumero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aposta')),
                ('numero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.numero')),
            ],
            options={
                'verbose_name': 'Número da aposta',
                'verbose_name_plural': 'Números das apostas',
                'db_table': 'aposta_numero',
            },
        ),
        migrations.AddField(
            model_name='aposta',
            name='numeros',
            field=models.ManyToManyField(related_name='apostas', through='core.ApostaNumero', to='core.numero'),
        ),
        migrations.CreateModel(
            name='ApostaSorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aposta')),
                ('sorteio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.sorteio')),
            ],
            options={
                'verbose_name': 'Sorteio apostado',
                'verbose_name_plural': 'Sorteios apostados',
                'db_table': 'aposta_sorteio',
            },
        ),
        migrations.CreateModel(
            name='ApostaResultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acertos', models.PositiveIntegerField()),
                ('acertos_espelhados', models.PositiveIntegerField()),
                ('aposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados', to='core.aposta')),
                ('sorteio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aposta_resultado', to='core.sorteio')),
            ],
            options={
                'verbose_name': 'Resultado da aposta',
                'verbose_name_plural': 'Resultados das apostas',
                'db_table': 'aposta_resultado',
            },
        ),
        migrations.CreateModel(
            name='ApostaPremio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.PositiveIntegerField(default=0, validators=[core.utils.validators.validar_pontos])),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('aposta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premios', to='core.aposta')),
                ('sorteio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aposta_premio', to='core.sorteio')),
            ],
            options={
                'verbose_name': 'Prêmio de Aposta',
                'verbose_name_plural': 'Prêmios de Apostas',
                'db_table': 'aposta_premio',
                'ordering': ['-aposta__data', '-pontos'],
            },
        ),
        migrations.AddField(
            model_name='aposta',
            name='sorteios',
            field=models.ManyToManyField(related_name='apostas', through='core.ApostaSorteio', to='core.sorteio'),
        ),
        migrations.CreateModel(
            name='SorteioNumero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.numero')),
                ('sorteio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sorteio')),
            ],
            options={
                'verbose_name': 'Número sorteado',
                'verbose_name_plural': 'Números sorteados',
                'db_table': 'sorteio_numero',
            },
        ),
        migrations.AddField(
            model_name='sorteio',
            name='numeros',
            field=models.ManyToManyField(related_name='sorteios', through='core.SorteioNumero', to='core.numero'),
        ),
        migrations.CreateModel(
            name='SorteioPremio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pontos', models.PositiveIntegerField(default=0, validators=[core.utils.validators.validar_pontos])),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ganhadores', models.PositiveIntegerField(default=0)),
                ('sorteio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='premios', to='core.sorteio')),
            ],
            options={
                'verbose_name': 'Prêmio do sorteio',
                'verbose_name_plural': 'Prêmios dos sorteios',
                'db_table': 'sorteio_premio',
            },
        ),
        migrations.AddConstraint(
            model_name='apostanumero',
            constraint=models.UniqueConstraint(fields=('aposta', 'numero'), name='unique_aposta_numero'),
        ),
        migrations.AddConstraint(
            model_name='apostasorteio',
            constraint=models.UniqueConstraint(fields=('aposta', 'sorteio'), name='unique_aposta_sorteio'),
        ),
        migrations.AddConstraint(
            model_name='apostaresultado',
            constraint=models.UniqueConstraint(fields=('aposta', 'sorteio'), name='unique_aposta_resultado'),
        ),
        migrations.AddConstraint(
            model_name='apostapremio',
            constraint=models.UniqueConstraint(fields=('aposta', 'sorteio', 'pontos'), name='unique_aposta_premio'),
        ),
        migrations.AddConstraint(
            model_name='sorteionumero',
            constraint=models.UniqueConstraint(fields=('sorteio', 'numero'), name='unique_sorteio_numero'),
        ),
    ]
