FROM python:3.14-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN python -m pip install --upgrade pip \
    && python -m pip install --no-cache-dir -r requirements.txt

COPY docker/entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

COPY . .

EXPOSE 8080

ENTRYPOINT ["/entrypoint.sh"]
